spring:
  cloud:
    gateway:
      routes:
      - id: quark-mongo-server
        order: 0
        predicates:
        - Path=/mongo/**
        uri: lb://quark-mongo
        filters:
        - Log
        - StripPrefix=1