spring:
  application:
    name: quark-mongo
  profiles:
    active: pro
  data:
    mongodb:
      authentication-database: blog
      uri: mongodb://maochunhua:20190514@localhost:27017/blog
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://maomao:mao123456@localhost:8761/eureka/
