server:
  port: 8777

spring:
  application:
    name: openstore-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shihuaguo/openstore-config.git
          searchPaths: /{application}
          username:
          password:
      label: master

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka